---
resources:
- name: movie-fun
  type: git
  source:
    uri: https://github.com/ganesanbbc/apps-movie-fun-code
    branch: spring-boot

- name: deploy-attendee-service
  type: cf
  source:
    api: https://api.system.cumuluslabs.io        #<---- REPLACE ME
    username: {{cf-user}}
    password: {{cf-password}}
    organization: nganesan-pal    #<---- REPLACE ME
    space: sandbox         #<---- REPLACE ME
    skip_cert_check: true

jobs:
#- name: test
#  public: true
#  plan:
#  - get: attendee-service-source
#    trigger: true
#  - task: test
#    file: attendee-service-source/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: movie-fun
    trigger: true
#    passed: [test]
  - task: package
    file: movie-fun/ci/package.yml
  - put: deploy-attendee-service
    params:
      manifest: movie-fun/manifest.yml
      path: package-output/moviefun.war

- name: smoke_test
  public: true
  plan:
  - get: movie-fun
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: movie-fun/ci/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: http://moviefun-baccate-uncausativeness.apps.cumuluslabs.io  #<---- REPLACE ME